---
- name: Include distribution install tasks
  ansible.builtin.include_tasks: "{{ loop_distribution }}"
  with_first_found:
    - files:
        - "install_grafana_{{ distribution | lower }}_{{ distribution_version | lower }}.yml"
        - "install_grafana_{{ distribution | lower }}_{{ distribution_major_version | lower }}.yml"
        - "install_grafana_{{ distribution | lower }}.yml"
        - "install_grafana_{{ ansible_os_family | lower }}.yml"
        - "install_grafana_{{ ansible_system | lower }}.yml"
        - "defaults.yml"
  loop_control:
    loop_var: loop_distribution
  vars:
    distribution: "{{ ansible_distribution }}"
    distribution_version: "{{ ansible_distribution_version }}"
    distribution_major_version: "{{ ansible_distribution_major_version }}"

- name: Include distribution configure tasks
  ansible.builtin.include_tasks: "{{ loop_distribution }}"
  with_first_found:
    - files:
        - "configure_grafana_{{ distribution | lower }}_{{ distribution_version | lower }}.yml"
        - "configure_grafana_{{ distribution | lower }}_{{ distribution_major_version | lower }}.yml"
        - "configure_grafana_{{ distribution | lower }}.yml"
        - "configure_grafana_{{ ansible_os_family | lower }}.yml"
        - "configure_grafana_{{ ansible_system | lower }}.yml"
        - "defaults.yml"
  loop_control:
    loop_var: loop_distribution
  vars:
    distribution: "{{ ansible_distribution }}"
    distribution_version: "{{ ansible_distribution_version }}"
    distribution_major_version: "{{ ansible_distribution_major_version }}"
