---

- name: Run arillso yum Repositories
  ansible.builtin.include_role:
    name: arillso.system.yum_repositories
  vars:
    yum_repositories:
      - name: digitalocean-agent
        description: DigitalOcean Agent
        baseurl: "https://repos.insights.digitalocean.com/yum/do-agent/$basearch"
        file: "digitalocean-agent"
        gpgkey: "https://repos.insights.digitalocean.com/sonar-agent.asc"
        gpgcheck: true
        state: present
        enabled: true
        metadata_expire: 300
        repo_gpgcheck: 0
        sslcacert: "/etc/pki/tls/certs/ca-bundle.crt"
        sslverify: 0
