---
- name: Run arillso apt Repositories
  ansible.builtin.include_role:
    name: arillso.system.apt_repositories
  vars:
    apt_repositories_list:
      - repo: "deb https://repos.insights.digitalocean.com/apt/do-agent main main"
        filename: "digitalocean-agent"

- name: Run arillso Package
  ansible.builtin.include_role:
    name: arillso.system.packages
  vars:
    packages_list: "{{ do_packages }}"
