argument_specs:
  main:
    short_description: Install Grafana Agent
    description:
      - Installs the Grafana Agent on the target system.
      - By default, the latest release of the Grafana Agent will be installed.
    options:
      grafana_version: &grafana_version
        type: str
        description:
          - The version of the Grafana Agent to install. Can be a specific version (e.g., "0.18.2")
          - or "latest" to install the latest release.  By default, "latest" will be used.
        default: "latest"
      grafana_log_level: &grafana_log_level
        type: str
        description:
          - The log level for the Grafana Agent service.
        default: "info"
      grafana_config_file: &grafana_config_file
        type: str
        description:
          - The path to the Grafana Agent configuration file.
        default: "/etc/grafana-agent.yaml"
      grafana_custom_args: &grafana_custom_args
        type: str
        description:
          - Additional command-line arguments to pass to the Grafana Agent service.
        default: "-server.http.address=127.0.0.1:9090 -server.grpc.address=127.0.0.1:9091"
      grafana_restart_on_upgrade: &grafana_restart_on_upgrade
        type: str
        description:
          - Whether to restart the Grafana Agent service when upgrading to a new version.
        default: "true"
      grafana_server: &grafana_server
        type: dict
        description:
          - Configuration options for the Grafana Agent server.
        default:
          log_level: warn
      grafana_metrics: &grafana_metrics
        type: dict
        description:
          - Configuration options for Grafana Agent metrics collection.
        default:
          global:
            scrape_interval: 1m
          configs:
            - name: integrations
      grafana_integrations: &grafana_integrations
        type: dict
        description:
          - Configuration options for Grafana Agent integrations.
        default:
          agent:
            enabled: true
      grafana_logs: &grafana_logs
        type: dict
        description:
          - The directory where Grafana Agent log positions are stored.
        default:
          positions_directory: "C:\\ProgramData\\grafana-agent-logs"

  configure_grafana_debian:
    short_description: Configure the Grafana Agent on Debian-based systems
    description:
      - Configures the Grafana Agent on Debian-based systems using the specified configuration file.
    options:
      grafana_config_file: *grafana_config_file
      grafana_custom_args: *grafana_custom_args
      grafana_restart_on_upgrade: *grafana_restart_on_upgrade
      grafana_server: *grafana_server
      grafana_metrics: *grafana_metrics
      grafana_integrations: *grafana_integrations
      grafana_logs: *grafana_logs

  configure_grafana_redhat:
    short_description: Configure Grafana Agent on Red Hat based systems
    description:
      - Configures the Grafana Agent on Red Hat based systems.
    options:
      grafana_config_file: *grafana_config_file
      grafana_custom_args: *grafana_custom_args
      grafana_restart_on_upgrade: *grafana_restart_on_upgrade
      grafana_server: *grafana_server
      grafana_metrics: *grafana_metrics
      grafana_integrations: *grafana_integrations
      grafana_logs: *grafana_logs

  configure_grafana_windows:
    short_description: Configure Grafana Agent on Windows
    description:
      - Configures the Grafana Agent on Windows systems.
    options:
      grafana_config_file: *grafana_config_file
      grafana_custom_args: *grafana_custom_args
      grafana_restart_on_upgrade: *grafana_restart_on_upgrade
      grafana_server: *grafana_server
      grafana_metrics: *grafana_metrics
      grafana_integrations: *grafana_integrations
      grafana_logs: *grafana_logs

  install_grafana_debian:
    short_description: Install Grafana Agent on Debian based systems
    description:
      - Installs the Grafana Agent on Debian based systems.
    options:
      grafana_version: *grafana_version

  install_grafana_redhat:
    short_description: Install Grafana Agent on Red Hat based systems
    description:
      - Installs the Grafana Agent on Red Hat based systems.
    options:
      grafana_version: *grafana_version

  install_grafana_windows:
    short_description: Install Grafana Agent on Windows
    description:
      - Installs the Grafana Agent on Windows systems.
    options:
      grafana_version: *grafana_version
