---
- name: Restart Windows Grafana Agent
  ansible.windows.win_service:
    name: "Grafana Agent"
    state: restarted

- name: Restart Linux Grafana Agent
  ansible.builtin.service:
    name: grafana-agent
    daemon_reload: true
    state: restarted
